// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6NouZjxyrBcrBIRmtAk0W-SVVCzEEmY',
    appId: '1:358701941979:web:b0c47cd25ae3ea806878fe',
    messagingSenderId: '358701941979',
    projectId: 'apptech-9928c',
    authDomain: 'apptech-9928c.firebaseapp.com',
    storageBucket: 'apptech-9928c.firebasestorage.app',
    measurementId: 'G-XJ9F1SQ4X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjgC4a-ZE33lpbT8Aukn4s0P-wDpJzvSc',
    appId: '1:358701941979:android:a24b1cb4d29315226878fe',
    messagingSenderId: '358701941979',
    projectId: 'apptech-9928c',
    storageBucket: 'apptech-9928c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuu_vMViUDb7N13XZdh3MAn2_0JqrrW_0',
    appId: '1:358701941979:ios:bd2d6474733e79c16878fe',
    messagingSenderId: '358701941979',
    projectId: 'apptech-9928c',
    storageBucket: 'apptech-9928c.firebasestorage.app',
    iosBundleId: 'com.kimyeomyeong.apptech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuu_vMViUDb7N13XZdh3MAn2_0JqrrW_0',
    appId: '1:358701941979:ios:bd2d6474733e79c16878fe',
    messagingSenderId: '358701941979',
    projectId: 'apptech-9928c',
    storageBucket: 'apptech-9928c.firebasestorage.app',
    iosBundleId: 'com.kimyeomyeong.apptech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe6NouZjxyrBcrBIRmtAk0W-SVVCzEEmY',
    appId: '1:358701941979:web:461ec69953ce3b036878fe',
    messagingSenderId: '358701941979',
    projectId: 'apptech-9928c',
    authDomain: 'apptech-9928c.firebaseapp.com',
    storageBucket: 'apptech-9928c.firebasestorage.app',
    measurementId: 'G-992MQ4SX1R',
  );

}